const $=s=>document.querySelector(s),cards=new Map(),states={listen:'倾听',think:'思考',comfort:'安慰',playful:'调皮',annoyed:'轻微不满',affirm:'肯定'};
let uploading=false,previewURL=null;
async function api(url,options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw Error(data.error||'请求失败');return data;}
function node(tag,text){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;return el;}
function card(a){
 let entry=cards.get(a.id);
 if(!entry){const el=node('article');el.className='avatar-card';const media=node('div'),body=node('div');body.className='avatar-body';const title=node('h3',a.name),status=node('p'),progress=node('progress');progress.max=1;body.append(title,status,progress);el.append(media,body);$('#avatars').append(el);entry={el,media,body,status,progress,mode:null};cards.set(a.id,entry);}
 const target=$(['failed','cancelled'].includes(a.status)?'#incomplete':'#avatars');if(entry.el.parentElement!==target)target.append(entry.el);
 entry.status.textContent=(a.motion_backend==='minimax-body'?'自然半身 · ':'')+(a.message||({ready:'已就绪 · 可预览六种动作',queued:'等待自动准备',preparing:'正在准备',failed:'准备失败，请换照片重新上传',cancelled:'已取消，可重新上传'}[a.status]));entry.progress.hidden=['ready','failed','cancelled'].includes(a.status);
 if(entry.mode!==a.status){entry.mode=a.status;entry.media.replaceChildren();entry.body.querySelector('.motions')?.remove();entry.body.querySelector('.use-avatar')?.remove();entry.body.querySelector('.work-avatar')?.remove();entry.body.querySelector('.cancel-prep')?.remove();entry.body.querySelector('.retry-prep')?.remove();entry.body.querySelector('.regenerate-prep')?.remove();
  if(a.status==='ready'){const video=node('video');video.src=a.asset_base+'/listen/motion.mp4';video.controls=true;video.muted=true;video.loop=true;video.playsInline=true;video.poster=a.poster;video.preload='metadata';entry.media.append(video);
   const motions=node('div');motions.className='motions';for(const [key,label] of Object.entries(states)){const b=node('button',label);b.setAttribute('aria-pressed',String(key==='listen'));b.onclick=()=>{video.src=a.asset_base+'/'+key+'/motion.mp4';motions.querySelectorAll('button').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));video.play().catch(()=>{});};motions.append(b);}entry.body.append(motions);const link=node('a','使用此人物对话 ↗');link.className='use-avatar';link.href='/chat?avatar='+encodeURIComponent(a.id);entry.body.append(link);const work=node('a','输入台词测试口型');work.className='work-avatar';work.href='/?avatar='+encodeURIComponent(a.id);entry.body.append(work);
  }else{const img=node('img');img.src=a.poster;img.alt=a.name;entry.media.append(img);if(['failed','cancelled'].includes(a.status)){const retry=node('button','继续准备');retry.className='retry-prep';retry.onclick=async()=>{retry.disabled=true;try{card(await api('/api/avatars/'+a.id+'/retry',{method:'POST'}));}catch(e){entry.status.textContent=e.message;retry.disabled=false;}};entry.body.append(retry);if(a.motion_backend==='minimax-body'&&a.status==='failed'){const again=node('button','重建失败动作（可能再次计费）');again.className='regenerate-prep';again.onclick=async()=>{again.disabled=true;try{card(await api('/api/avatars/'+a.id+'/retry?regenerate=1',{method:'POST'}));}catch(e){entry.status.textContent=e.message;again.disabled=false;}};entry.body.append(again);}}if(['queued','preparing'].includes(a.status)){const cancel=node('button','取消准备');cancel.className='cancel-prep';cancel.onclick=async()=>{cancel.disabled=true;try{await api('/api/cancel/'+a.job,{method:'POST'});}catch(e){entry.status.textContent=e.message;cancel.disabled=false;}};entry.body.append(cancel);}}
 }
 if(a.job&&!['ready','failed','cancelled'].includes(a.status))api('/api/jobs/'+a.job).then(job=>{entry.progress.value=job.progress||0;entry.status.textContent=job.message;}).catch(()=>{});
}
async function refresh(){try{const data=await api('/api/avatars');data.avatars.forEach(card);$('#upload').disabled=uploading||data.busy;$('#library-status').textContent=data.busy?'正在使用生成资源。可以预览已完成的人物；新上传请等待当前任务结束。':(data.avatars.some(a=>a.status==='failed'&&(a.message||'').includes('2056'))?'最近一次自然半身准备遇到 MiniMax 额度限制（2056）。已有视频可播放，本地面部准备仍可使用。':'准备好的人物可以直接用于新对话。');}catch(e){$('#library-status').textContent=e.message;}finally{setTimeout(refresh,1500);}}
$('#photo').onchange=()=>{if(previewURL)URL.revokeObjectURL(previewURL);const f=$('#photo').files[0];$('#upload-preview').hidden=!f;if(f){previewURL=URL.createObjectURL(f);$('#upload-preview').src=previewURL;}};
$('#upload-form').onsubmit=async e=>{e.preventDefault();if(uploading)return;const file=$('#photo').files[0];if(!file)return;if(file.size>12*1024*1024){$('#upload-status').textContent='照片需小于 12 MB';return;}uploading=true;$('#upload').disabled=true;$('#upload-status').textContent='正在上传照片…';try{const a=await api('/api/avatars?name='+encodeURIComponent($('#avatar-name').value)+'&motion_backend='+encodeURIComponent($('#motion-backend').value),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});card(a);$('#upload-status').textContent='照片已接收，准备进度见右侧。页面关闭后仍会继续，可稍后回来查看。';}catch(e){$('#upload-status').textContent=e.message;}finally{uploading=false;}};
refresh();

$('#motion-backend').onchange=()=>{$('#backend-hint').textContent=$('#motion-backend').value==='minimax-body'?'将照片发送至 MiniMax，生成六段视频，使用账户视频额度；云端已提交任务可能继续计费。':'全部在本机准备面部和头部动作，身体保持照片。';};
