const $=s=>document.querySelector(s),actor=$('#actor'),idle=$('#idle'),stage=$('.stage');let clips=[],selected=null,mode='complete',queue=[],token=0,muted=false;
const descriptions={complete:'收尾修正版：尾音结束后嘴部平滑回到放松状态。',before:'上一版：口腔映射已修正，但静音尾段仍持续生成嘴型。重点观察“还好吗”之后。',motion:'生成嘴型前的原始动作视频，没有音轨。',photo:'生成动作前的原始照片。'};
function modes(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode));$('#mode-description').textContent=descriptions[mode];}
function rest(){token++;actor.pause();queue=[];mode='complete';modes();stage.classList.remove('active','photo');idle.play().catch(()=>{});$('#state').textContent='休息一下';$('#time').textContent='已停止';}
async function show(clip,seek=0){const own=++token;selected=clip;actor.pause();stage.classList.remove('active');stage.classList.toggle('photo',mode==='photo');$('#reply').textContent=clip.text;$('#subtitle').textContent=mode==='motion'?'原始动作 · 未添加语音与新嘴型':mode==='photo'?'原始照片 · 静态参考':clip.text;$('#state').textContent=clip.name;$('#replay').disabled=false;$('#download').href=clip.video;$('#download').hidden=false;document.querySelectorAll('.scene').forEach(b=>b.setAttribute('aria-pressed',b.dataset.id===clip.id));if(mode==='photo'){idle.pause();return;}actor.muted=mode==='motion'||muted;actor.src=mode==='complete'?clip.video:mode==='before'?clip.before_video:clip.source_video;actor.load();try{await actor.play();if(own!==token)return;if(seek>0&&seek<actor.duration)actor.currentTime=seek;stage.classList.add('active');idle.pause();}catch(e){if(own===token)$('#time').textContent='请点重播';}}
$('#interrupt').onclick=()=>{rest();$('#subtitle').textContent='播放已停止，随时可以再听一段。';};$('#replay').onclick=()=>{queue=[];if(selected)show(selected);};$('#play-all').onclick=()=>{mode='complete';modes();queue=clips.slice(1);show(clips[0]);};
$('#mute').onclick=()=>{muted=!muted;actor.muted=mode==='motion'||muted;$('#mute').textContent=muted?'声音关':'声音开';};
$('#focus').onclick=()=>{document.body.classList.toggle('focus');$('#focus').textContent=document.body.classList.contains('focus')?'返回完整视图 ↙':'陪伴视图 ↗';};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{const seek=actor.currentTime;queue=[];mode=b.dataset.mode;modes();if(selected)show(selected,seek);else{stage.classList.toggle('photo',mode==='photo');if(mode==='photo')idle.pause();else idle.play().catch(()=>{});}});
actor.ontimeupdate=()=>{if(!actor.paused)$('#time').textContent=`${actor.currentTime.toFixed(1)} / ${actor.duration.toFixed(1)} s`;};
actor.onended=async()=>{if(queue.length){show(queue.shift());return;}const own=token;if(mode==='complete'&&selected?.idle_video){idle.src=selected.idle_video;idle.load();}try{await idle.play();if(own!==token)return;stage.classList.remove('active');}catch(e){if(own!==token)return;}$('#state').textContent='等你回应';$('#time').textContent='播放完毕';};
actor.onerror=()=>{if(selected)$('#time').textContent='视频加载失败';};
async function init(){const r=await fetch('/api/complete');if(!r.ok)throw Error('完整效果服务连接失败');const data=await r.json();clips=data.clips;const list=$('#scenes');list.replaceChildren();for(const [i,clip] of clips.entries()){const b=document.createElement('button');b.className='scene';b.dataset.id=clip.id;b.setAttribute('aria-pressed','false');const icon=document.createElement('span');icon.className='icon';icon.textContent=['☀','✧','♡'][i];const words=document.createElement('span'),title=document.createElement('strong'),line=document.createElement('small');title.textContent=clip.name;line.textContent=clip.text;words.append(title,line);const arrow=document.createElement('span');arrow.className='arrow';arrow.textContent='↗';b.append(icon,words,arrow);b.onclick=()=>{queue=[];show(clip);};list.append(b);}$('#play-all').disabled=!clips.length;$('#metrics').textContent=clips.length?`${clips.length} 段实际输出 · 512 × 768 · 30 fps。点击场景后播放缓存结果。`:'正在生成完整效果。';if(data.montage){$('#montage').href=data.montage;$('#montage').hidden=false;}if(clips.length<3)setTimeout(()=>init().catch(e=>$('#status').textContent=e.message),5000);}
init().catch(e=>$('#status').textContent=e.message);
