const $=s=>document.querySelector(s),idle=$('#idle'),actor=$('#actor'),audio=$('#audio');
let session=null,active=null,epoch=0,poll=null,lastResult=null,configured=false,muted=false,mode='listen',replySeen=new Set(),submitting=false;
const names={listen:'倾听',think:'思考',comfort:'安慰',playful:'调皮',annoyed:'轻微不满',affirm:'肯定'};
async function api(path,data){const r=await fetch(path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await r.json();if(!r.ok)throw Error(value.error||'请求失败');return value;}
function stage(state){actor.pause();actor.hidden=true;idle.hidden=false;if(mode!==state){mode=state;idle.src='/assets/'+state+'/motion.mp4';}idle.play().catch(()=>{});$('#state').textContent=state==='think'?'正在准备回应':'我在听';}
function message(role,text,key){if(key&&replySeen.has(key))return;if(key)replySeen.add(key);$('#messages .empty')?.remove();const p=document.createElement('p');p.className='message '+role;const label=document.createElement('small');label.textContent=role==='user'?'你':'小晴';p.append(label,document.createTextNode(text));$('#messages').append(p);$('#messages').scrollTop=$('#messages').scrollHeight;}
function controls(){const busy=Boolean(active)||submitting;$('#send').disabled=!configured||busy;$('#new-session').disabled=busy;document.querySelectorAll('.suggestions button').forEach(b=>b.disabled=!configured||busy);}
async function refresh(){const s=await api('/api/dialogue/status');configured=s.provider.configured&&s.worker.status==='ready';$('#setup').hidden=s.provider.configured;$('#connection').textContent=s.provider.configured?'MiniMax · 已配置':'MiniMax · 待配置';$('#models').textContent='对话：'+s.provider.chat_model+'；语音：'+s.provider.speech_model+'。';if(!configured)$('#status').textContent=s.provider.configured?'人物模型正在准备…':'请先配置 MiniMax，再开始对话。';controls();return s;}
async function loadSession(key){session=key?await api('/api/dialogue/session/'+key):await api('/api/dialogue/session',{});sessionStorage.setItem('xiaoqing-dialogue',session.id);history.replaceState(null,'','/chat?session='+session.id);$('#messages').replaceChildren();replySeen=new Set();for(const m of session.messages)message(m.role,m.content,m.role==='assistant'?m.job:null);if(!session.messages.length){const p=document.createElement('p');p.className='empty';p.textContent='这里是你和小晴的对话。回复由 MiniMax 根据上下文生成。';$('#messages').append(p);}}
async function play(item){lastResult=item;$('#replay').disabled=false;audio.pause();idle.pause();idle.hidden=true;actor.hidden=false;actor.src=item.video;actor.muted=muted;$('#state').textContent=names[item.state]+' · 回应你';$('#subtitle').textContent=item.text;$('#result-controls').hidden=false;$('#play-ready').hidden=true;$('#download').hidden=false;$('#download').href=item.video;const m=item.metrics;$('#timing').textContent='本轮等待 '+m.total_s.toFixed(1)+' 秒；对话 '+(item.chat_s||0).toFixed(1)+' 秒，语音 '+(item.tts_s||0).toFixed(1)+' 秒，画面 '+m.render_s.toFixed(1)+' 秒。';try{await actor.play();$('#status').textContent='她正在回应你，可以随时打断。';}catch{$('#play-ready').hidden=false;$('#status').textContent='回应已准备好，点击播放。';}}
actor.onended=()=>{stage('listen');$('#subtitle').textContent='我在听，你继续说。';$('#status').textContent='可以继续聊，或分享下一件小事。';};
async function watch(token){if(token!==epoch||!active)return;try{const item=await api('/api/jobs/'+active.id);if(token!==epoch)return;active=item;$('#status').textContent=item.message;$('#progress').value=item.progress||0;if(item.text)message('assistant',item.text,item.id);if(item.audio){if(audio.getAttribute('src')!==item.audio)audio.src=item.audio;$('#result-controls').hidden=false;$('#audio-only').hidden=false;}if(['done','failed','cancelled'].includes(item.status)){active=null;controls();if(item.status==='done')await play(item);else{stage('listen');$('#subtitle').textContent=item.status==='cancelled'?'我在听，你继续说。':'这次没能完成表演，可以继续聊。';}return;}poll=setTimeout(()=>watch(token),500);}catch(e){if(token!==epoch)return;$('#status').textContent=e.message;stage('listen');active=null;controls();}}
async function send(text,event){if(!configured||active||submitting||!text.trim())return;const token=++epoch;submitting=true;controls();audio.pause();stage('think');$('#subtitle').textContent='听到了，给我一点时间。';$('#progress').value=0;$('#status').textContent='正在把这句话交给 MiniMax…';try{const item=await api('/api/dialogue/turn',{session:session.id,text,event});if(token!==epoch){await api('/api/cancel/'+item.id,{});return;}message('user',text);$('#message').value='';active=item;$('#result-controls').hidden=true;$('#download').hidden=true;$('#audio-only').hidden=true;$('#replay').disabled=true;watch(token);}catch(e){if(token===epoch){stage('listen');$('#status').textContent=e.message;}}finally{submitting=false;controls();}}
async function interrupt(){const item=active;++epoch;clearTimeout(poll);audio.pause();stage('listen');$('#subtitle').textContent='好，我在听。';if(!item){$('#status').textContent='已停声，可以继续说。';return;}active=null;submitting=true;controls();try{await api('/api/cancel/'+item.id,{});$('#status').textContent='已停止播放，正在停止后台生成…';const end=Date.now()+70000;while(Date.now()<end){const s=await api('/api/dialogue/status');if(!s.busy){$('#status').textContent='已打断，可以继续说。';break;}await new Promise(r=>setTimeout(r,400));}}catch(e){$('#status').textContent=e.message;}finally{submitting=false;controls();}}
$('#composer').onsubmit=e=>{e.preventDefault();send($('#message').value);};$('#message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send($('#message').value);}};
document.querySelectorAll('[data-text]').forEach(b=>b.onclick=()=>send(b.dataset.text));$('#task-done').onclick=()=>send('我刚完成了一个任务，想听你鼓励一下。','task_done');
$('#interrupt').onclick=interrupt;$('#new-session').onclick=async()=>{await interrupt();await loadSession(null);lastResult=null;$('#replay').disabled=true;$('#result-controls').hidden=true;$('#status').textContent='新对话已开始。';};$('#refresh-config').onclick=async()=>{await refresh();if(configured)$('#status').textContent='MiniMax 配置已就绪，可以开始聊。';};
$('#replay').onclick=()=>lastResult&&play(lastResult);$('#play-ready').onclick=()=>lastResult&&play(lastResult);$('#audio-only').onclick=()=>{stage('listen');$('#state').textContent='语音模式 · 画面为待机';audio.muted=muted;audio.play().catch(()=>{});};$('#mute').onclick=()=>{muted=!muted;actor.muted=muted;audio.muted=muted;$('#mute').textContent=muted?'声音关':'声音开';};
async function init(){await refresh();const key=new URLSearchParams(location.search).get('session')||sessionStorage.getItem('xiaoqing-dialogue');try{await loadSession(key);}catch{await loadSession(null);}if(configured)$('#status').textContent='可以开始聊。文字回复先出现，声音和画面生成后一起播放。';const recent=session.messages.at(-1);if(recent){try{const item=await api('/api/jobs/'+recent.job);if(item.status==='done'){lastResult=item;$('#replay').disabled=false;}else if(['thinking','tts','queued','rendering'].includes(item.status)){active=item;stage('think');controls();watch(++epoch);}}catch{}}}
init().catch(e=>$('#status').textContent='连接失败：'+e.message);
