const avatarId=new URLSearchParams(location.search).get('avatar')||'xiaoqing';
const $=s=>document.querySelector(s),video=$('#stage');let assets=[],selected=null,job=null,result=null,poll=null;
function preview(asset){selected=asset;$('#audio').pause();$('#name').textContent=asset.name;$('#description').textContent=asset.description;$('#kind').textContent='动作预览 · 无声';video.pause();video.src=asset.video;video.loop=true;video.muted=true;video.play().catch(()=>{});document.querySelectorAll('.asset').forEach(b=>b.setAttribute('aria-pressed',b.dataset.id===asset.id));}
function playResult(item){result=item;$('#play-result').disabled=false;$('#download').hidden=false;$('#download').href=item.video;$('#kind').textContent='新台词 · 有声结果';const asset=assets.find(a=>a.id===item.state);if(asset){selected=asset;document.querySelectorAll('.asset').forEach(b=>b.setAttribute('aria-pressed',b.dataset.id===asset.id));}$('#name').textContent=asset?.name||'生成结果';$('#description').textContent=item.text;$('#audio').pause();if(item.audio){$('#audio').src=item.audio;$('#audio-section').hidden=false;}video.pause();video.src=item.video;video.loop=false;video.muted=false;video.play().catch(()=>{$('#status').textContent='视频已就绪，点击播放新视频。';});showMetrics(item.metrics);}
function showMetrics(metrics){const box=$('#metrics');box.replaceChildren();if(!metrics)return;for(const [title,value,unit] of [['语音就绪',metrics.tts_s,'秒'],['嘴型推理',metrics.lip_inference_s,'秒'],['端到端等待',metrics.total_s,'秒'],['输出时长',metrics.media_duration_s,'秒'],['处理/片长',metrics.processing_realtime_factor,'倍'],['GPU 峰值',metrics.gpu_peak_allocated_mb,'MB']]){const d=document.createElement('div');d.className='metric';const s=document.createElement('span');s.textContent=title;const b=document.createElement('strong');b.textContent=value??'—';const small=document.createElement('small');small.textContent=' '+unit;b.append(small);d.append(s,b);box.append(d);}}
async function watch(){clearTimeout(poll);if(!job)return;const own=job.id;try{const r=await fetch('/api/jobs/'+own);const data=await r.json();if(job?.id!==own)return;job=data;$('#status').textContent=data.message;$('#progress').value=data.progress||0;if(data.audio){$('#audio-section').hidden=false;if($('#audio').getAttribute('src')!==data.audio)$('#audio').src=data.audio;}
 if(['done','failed','cancelled'].includes(data.status)){clearTimeout(poll);$('#generate').disabled=false;$('#cancel').disabled=true;if(data.status==='done'){playResult(data);addHistory(data);}return;}
 poll=setTimeout(watch,600);}catch(e){$('#status').textContent='连接中断，稍后可刷新查看任务';$('#generate').disabled=false;$('#cancel').disabled=true;}}
function addHistory(item){if(!item.video||item.benchmark_replay_of||document.querySelector('[data-job="'+item.id+'"]'))return;const b=document.createElement('button');b.dataset.job=item.id;b.textContent=item.text.slice(0,18)+({'performance-v2':' · 加速版','performance-v3-overlap':' · 衔接优化版'}[item.metrics?.pipeline_version]||' · 原版');b.onclick=()=>playResult(item);$('#history').prepend(b);}
$('#generate').onclick=async()=>{if(!selected)return;video.pause();$('#audio').pause();$('#generate').disabled=true;$('#cancel').disabled=true;$('#progress').value=0;$('#status').textContent='提交新台词…';try{const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('#text').value,state:selected.id,avatar_id:avatarId})});const d=await r.json();if(!r.ok)throw Error(d.error);job=d;$('#cancel').disabled=false;$('#audio-section').hidden=true;$('#play-result').disabled=true;$('#download').hidden=true;showMetrics(null);watch();}catch(e){$('#status').textContent=e.message;$('#generate').disabled=false;}};
$('#cancel').onclick=async()=>{if(!job)return;await fetch('/api/cancel/'+job.id,{method:'POST'});$('#status').textContent='正在取消生成…';watch();};
$('#preview').onclick=()=>{if(selected)preview(selected);};$('#play-result').onclick=()=>{if(result)playResult(result);};$('#text').oninput=()=>$('#count').textContent=$('#text').value.length+' / 80';$('#text').oninput();
async function init(){const r=await fetch('/api/workbench?avatar='+encodeURIComponent(avatarId));const data=await r.json();if(!r.ok)throw Error(data.error);$('#chat-link').href='/chat?avatar='+avatarId;assets=data.assets;$('#assets').replaceChildren();for(const a of assets){const b=document.createElement('button');b.className='asset';b.dataset.id=a.id;b.setAttribute('aria-pressed','false');const img=document.createElement('img');img.src=a.poster;img.alt='';const label=document.createElement('strong');label.textContent=a.name;b.append(img,label);b.onclick=()=>preview(a);$('#assets').append(b);}preview(assets[0]);$('#worker').textContent=data.worker.status==='ready'?'模型已预热':'模型准备中';$('#status').textContent=data.worker.status==='ready'?'可输入新台词，生成真实有声视频。':'模型正在预热，请稍后提交。';for(const item of data.jobs.filter(j=>j.status==='done').reverse())addHistory(item);if(data.worker.status!=='ready')setTimeout(init,3000);}
async function loadComparison(){
 const response=await fetch('performance-comparison.json');if(!response.ok)return;
 const data=await response.json();$('#speed-comparison').replaceChildren();
 for(const item of data.samples){
  const name=assets.find(a=>a.id===item.state)?.name||item.state;
  const row=document.createElement('div');row.className='speed-row';
  const text=document.createElement('p');text.textContent=name+'：'+item.baseline_metrics.total_s.toFixed(1)+' 秒 → '+item.new_metrics.total_s.toFixed(1)+' 秒';
  const actions=document.createElement('div');actions.className='actions';
  for(const [key,label] of [[item.baseline_job,'优化前'],[item.new_job,'加速版']]){
   const button=document.createElement('button');button.textContent=label;button.setAttribute('aria-label',name+'：播放'+label);
   button.onclick=async()=>{try{const r=await fetch('/api/jobs/'+key);if(!r.ok)throw Error('样例不可用');const sample=await r.json();playResult(sample);$('#kind').textContent=label+' · 有声结果';}catch(e){$('#status').textContent=e.message;}};actions.append(button);
  }
  row.append(text,actions);$('#speed-comparison').append(row);
 }
 $('#comparison-section').hidden=false;
}
init().then(()=>{if(avatarId==='xiaoqing')return loadComparison();}).catch(e=>$('#status').textContent='服务连接失败：'+e.message);
