'use strict';
const $=id=>document.getElementById(id);let sampleImage='',sampleAudio='',selectedImage=null,selectedAudio=null,busy=false,timer=null,started=0;
async function request(url,options){const r=await fetch(url,options);const body=await r.json();if(!r.ok)throw new Error(body.error||'请求失败');return body;}
async function useExampleInputs(){const [picture,recording]=await Promise.all([fetch(sampleImage).then(r=>r.blob()),fetch(sampleAudio).then(r=>r.blob())]);selectedImage=new File([picture],'example-portrait.png',{type:'image/png'});selectedAudio=new File([recording],'example-audio.wav',{type:'audio/wav'});$('portrait').src=sampleImage;$('source-audio').src=sampleAudio;$('audio-name').textContent='示例中文录音 · 9.4 秒';}
function showResult(job){$('empty').hidden=true;$('busy').hidden=true;$('result').hidden=false;$('result').src=job.video;$('download').href=job.video;$('download').hidden=false;$('state').textContent='已生成';$('detail').textContent=`${job.duration.toFixed(1)} 秒口播 · 本机生成用时 ${job.seconds.toFixed(1)} 秒`;$('message').textContent=job.message;}
function buttons(){ $('generate').disabled=busy||!selectedImage||!selectedAudio;$('sample').disabled=busy;$('image').disabled=busy;$('recording').disabled=busy;}
function finish(){busy=false;clearInterval(timer);buttons();}
async function poll(id){try{const job=await request('/api/jobs/'+id);$('progress').textContent=job.message;if(job.status==='done'){showResult(job);finish();}else if(job.status==='failed'){throw new Error(job.message);}else setTimeout(()=>poll(id),1800);}catch(e){$('message').textContent=e.message;$('busy').hidden=true;$('state').textContent='生成失败';finish();}}
async function generate(useSample){if(busy)return;busy=true;buttons();$('busy').hidden=false;$('empty').hidden=true;$('download').hidden=true;$('state').textContent='生成中';$('message').textContent='首次运行需要加载模型，耗时会随照片、音频长度和显存占用变化。';started=Date.now();timer=setInterval(()=>$('elapsed').textContent='已等待 '+Math.floor((Date.now()-started)/1000)+' 秒',1000);
try{const form=new FormData();if(useSample){await useExampleInputs();form.append('sample','1');$('portrait').src=sampleImage;$('source-audio').src=sampleAudio;$('audio-name').textContent='示例中文录音';}else{form.append('image',selectedImage);form.append('audio',selectedAudio);}const job=await request('/api/generate',{method:'POST',body:form});poll(job.id);}catch(e){$('message').textContent=e.message;$('state').textContent='未生成';$('busy').hidden=true;finish();}}
$('image').onchange=e=>{const f=e.target.files[0];if(!f)return;selectedImage=f;$('portrait').src=URL.createObjectURL(f);buttons();$('input-hint').textContent=selectedAudio?'照片和录音已就绪。':'请再选择一段录音。';};
$('recording').onchange=e=>{const f=e.target.files[0];if(!f)return;selectedAudio=f;$('source-audio').src=URL.createObjectURL(f);$('audio-name').textContent=f.name;buttons();$('input-hint').textContent=selectedImage?'照片和录音已就绪。':'请再选择一张人物照片。';};
$('generate').onclick=()=>generate(false);$('sample').onclick=()=>generate(true);
request('/api/status').then(async s=>{sampleImage=s.sample_image;sampleAudio=s.sample_audio;$('portrait').src=sampleImage;$('source-audio').src=sampleAudio;$('audio-name').textContent='示例中文录音 · 9.4 秒';if(!s.ready)throw new Error('本机模型尚未准备完成。');await useExampleInputs();$('input-hint').textContent='可直接试用示例，或更换照片和录音。';buttons();if(s.example)showResult(s.example);}).catch(e=>{$('input-hint').textContent=e.message;});
