import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';

// These are original demonstrations inspired by the upstream techniques, not
// additions to its ability registry. No external assets or services are used.
const items = [
  {id:'fireflies',group:'effects',title:'萤火微光',sub:'漂浮粒子 · 呼吸闪烁',type:'ambient',mode:0,purpose:'让一个安静场景有生命感',description:'微光在三维空间缓慢漂移，大小和亮度随时间变化。调整密度，比较点缀式氛围与密集星尘。',extension:'可延伸为夜间庭院、虚拟展厅背景、阅读页面的轻量环境层，或让粒子向某个交互目标聚集。',boundary:'本例不含生态模拟；接入真实场景后需控制粒子遮挡和设备负载。',action:'切换风向'},
  {id:'snow',group:'effects',title:'飘雪',sub:'持续下落 · 横向风场',type:'ambient',mode:1,purpose:'展示季节与天气氛围',description:'不同深度的雪点以不同速度下落，风向按钮改变横向漂移。暂停后仍可调节密度与颜色。',extension:'冬季活动首页、气象展示、三维街景与节日电子卡片。也可增加地面累积和屋檐遮挡。',boundary:'目前只有视觉降雪，没有积雪、碰撞或真实天气数据。',action:'切换风向'},
  {id:'petals',group:'effects',title:'落花与花瓣',sub:'粉色片状粒子 · 翻转飘落',type:'ambient',mode:2,color:'#ff93bb',purpose:'用柔和运动表达季节与情绪',description:'花瓣在空中旋转、摇摆和下落；片状轮廓与雪点不同，适合观察同一粒子机制的视觉变体。',extension:'婚礼网页、春季品牌活动、园林预览，或产品揭幕后的装饰性散落。',boundary:'轮廓由着色器绘制；特定花型与真实空气动力学需要另外制作。',action:'切换风向'},
  {id:'confetti',group:'effects',title:'庆祝彩纸',sub:'多色纸片 · 喷发与重力',type:'ambient',mode:3,color:'#f7ba69',purpose:'让完成与成功具有可见反馈',description:'彩纸从中心喷出，沿抛物线散开。重播可重新触发完整爆发，进度滑块可以检查任意瞬间。',extension:'活动开幕、里程碑达成、发布会倒计时结束与互动抽奖揭晓。',boundary:'正式页面应按事件触发并及时结束；本例为方便观察而循环。',action:'重新喷发'},
  {id:'flow',group:'effects',title:'能量与数据流',sub:'沿曲线流动 · 节点点亮',type:'network',purpose:'把抽象连接变成可追踪的过程',description:'发光粒子沿节点间的路径移动，节点依次点亮。速度控制影响传播过程。',extension:'网络拓扑、设备连接、能量输送与业务流程。可将粒子频率映射为流量或请求量。',boundary:'本例使用演示信号；接入业务时需明确定义数值与视觉的对应关系。',action:'反转流向'},
  {id:'assembly',group:'effects',title:'零件聚合',sub:'分散 → 对位 → 组装',type:'product',purpose:'展示一个物体怎样组成',description:'外壳、散热片和核心从分散位置回到装配位置。展开按钮切换持续拆解状态，方便旋转观察。',extension:'设备拆解、建筑模块组合、包装结构与家具安装步骤。',boundary:'当前使用原创示意零件；真实产品需要三维模型、零件层级和装配位置。',action:'展开 / 组装'},
  {id:'dissolve',group:'effects',title:'文字粒子化',sub:'聚合文字 · 扩散消失',type:'logo',purpose:'让文字出现与消失成为一段演出',description:'粒子聚合成 NOVA 字样，再散回空间。点击切换聚散，观察同一组点如何在形状与背景间转换。',extension:'品牌标识、片头标题、产品揭幕与页面转场。可替换为自己的文字或图案轮廓。',boundary:'这里是点阵形变，不是任意模型的表面燃烧；导出视频需要补充录制流程。',action:'切换聚散'},
  {id:'scan',group:'effects',title:'空间扫描',sub:'扫描平面 · 轮廓浮现',type:'scan',purpose:'让检查范围与检查顺序可见',description:'发光扫描面穿过一组几何结构，附近轮廓变亮。进度条可冻结扫描位置。',extension:'仓储盘点、空间定位、设备检测、模型选中提示与展品介绍。',boundary:'扫描只做视觉表达，没有识别物体、检测故障或获取空间数据。',action:'重新扫描'},
  {id:'trail',group:'effects',title:'动作光迹',sub:'关节运动 · 双手轨迹',type:'motion',purpose:'把短暂动作保留为可见轨迹',description:'示意人物双手运动时留下渐隐光迹，切换动作可比较两种轨迹。暂停后保留运动形状。',extension:'舞蹈表演、运动教学、角色施法、签名手势与动画分镜。',boundary:'人物为程序化关节示意；真实角色需绑定骨骼并同步动作时间。',action:'切换动作'},
  {id:'portal',group:'effects',title:'空间光环',sub:'旋转环带 · 粒子旋涡',type:'portal',purpose:'给一个入口建立明确视觉焦点',description:'同心光环、旋转刻度与流动粒子组成入口效果。切换旋向可改变整体流动感。',extension:'展厅入口、章节切换、舞台背景与新品发布的揭幕装饰。',boundary:'没有异空间渲染和真正穿门传送；这些需要额外的相机与场景机制。',action:'切换旋向'},
  {id:'product',group:'scenes',title:'产品展示 · 从零件到启动',sub:'01 / PRODUCT STORY',type:'product',purpose:'让观众看懂设备的结构和运行顺序',description:'以示意能量装置为例：零件汇合 → 外壳成形 → 核心点亮 → 能量环运行。展开模式可以停留在拆解视图，拖动观察内部。',extension:'替换成真实产品模型；增加零件点击说明、装配步骤、热点标注。将运行颜色和频率接入真实传感器，扩展成设备状态展示。',boundary:'当前是原创示意装置，光效不代表电流或温度测量。真实应用需模型和数据接口。',action:'展开 / 组装'},
  {id:'brand',group:'scenes',title:'品牌网页 · 粒子揭幕',sub:'02 / BRAND EXPERIENCE',type:'logo',color:'#a9a0ff',purpose:'把品牌出现变成一次短小的视觉体验',description:'游离星尘聚合成 NOVA 字样，在环形舞台前停留，再散开。切换聚散按钮模拟用户触发的揭幕与退出。',extension:'替换为品牌标志，绑定首屏进入、滚动进度或发布按钮；可继续做产品揭幕、章节转场和片头包装。',boundary:'NOVA 为演示占位文字。正式网页需提供静态或低动态版本，并与页面内容布局配合。',action:'切换聚散'},
  {id:'education',group:'scenes',title:'教学演示 · 一条消息的旅程',sub:'03 / EXPLAIN A PROCESS',type:'network',purpose:'让信息经过哪些步骤一目了然',description:'消息从发送端出发，经过编码、传输、解码，抵达接收端。节点标签和底部阶段提示随进度变化；暂停或拖动进度可以逐步讲解。',extension:'把节点替换为真实业务流程，加入延迟、排队、丢包或重试，比较不同参数如何影响过程；也适用于订单流转与任务调度教学。',boundary:'当前为简化流程示意，不是网络协议模拟器，也没有真实吞吐量指标。',action:'反转流向'},
  {id:'performance',group:'scenes',title:'人物演出 · 动作留下光',sub:'04 / MOTION & PERFORMANCE',type:'motion',color:'#75b6ff',purpose:'把动作节奏和空间路径一起呈现',description:'程序化人物进行挥臂演出，手部轨迹组成光带，脚下圆环提供舞台定位。切换动作、慢放和暂停可比较两个动作方案。',extension:'接入 CozyClay 或其他工具导出的兼容角色动作，让光迹跟随骨骼；进一步同步镜头、音乐节拍和关键时刻的粒子爆发。',boundary:'当前没有接入 CozyClay、真人动作捕捉或音频分析；需适配骨骼、坐标与时间线。',action:'切换动作'},
  {id:'exhibition',group:'scenes',title:'互动展览 · 触碰星群',sub:'05 / PARTICIPATORY SPACE',type:'interactive',purpose:'让观众成为画面变化的触发者',description:'在画面中移动鼠标，星群会朝指针附近聚拢；点击画面或“触发波纹”产生扩散光环。可以直接体验“输入 → 视觉反馈”的闭环。',extension:'将鼠标坐标替换成手势、深度摄像头或地面感应位置，扩展为多人光墙、数字展品导览和公共空间互动。',boundary:'本例只使用鼠标或触屏；摄像头、手势识别和多人追踪都需要另外接入。',action:'触发波纹'}
];

const $=s=>document.querySelector(s),TAU=Math.PI*2,clamp=THREE.MathUtils.clamp;
let selected,group='scenes',t=0,paused=false,alternate=false,speed=1,density=.75,pulse=-100,accent=new THREE.Color('#66e3cf');
let renderer,scene,camera,controls,composer,root,updateScene=()=>{},materials=[],particleSets=[],labels=[];
const pointer=new THREE.Vector3(),clock=new THREE.Clock(),duration=12;
const seed=i=>{const x=Math.sin(i*127.1+311.7)*43758.5453;return x-Math.floor(x);};
const ease=x=>{x=clamp(x,0,1);return x*x*(3-2*x);};
const cyc=(time,period=12)=>((time%period)+period)%period/period;
function mesh(geometry,color=0x233f4c,metal=.6){const mat=new THREE.MeshStandardMaterial({color,metalness:metal,roughness:.32});const m=new THREE.Mesh(geometry,mat);root.add(m);return m;}
function glow(geometry){const mat=new THREE.MeshBasicMaterial({color:accent.clone(),transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false});materials.push(mat);const m=new THREE.Mesh(geometry,mat);root.add(m);return m;}
function ring(radius,y=0){const m=glow(new THREE.TorusGeometry(radius,.023,6,96));m.rotation.x=Math.PI/2;m.position.y=y;return m;}
function label(text,position){const el=document.createElement('span');el.className='node-label';el.textContent=text;$('#labels').append(el);labels.push({el,position});}
function points(count,kind=0,targets=null){
  const geo=new THREE.BufferGeometry(),pos=new Float32Array(count*3),seeds=new Float32Array(count*4);
  for(let i=0;i<count;i++){for(let j=0;j<4;j++)seeds[i*4+j]=seed(i*4+j);if(kind===6)seeds[i*4+3]=1-i/count;if(targets)pos.set(targets[i%targets.length],i*3);}
  geo.setAttribute('position',new THREE.BufferAttribute(pos,3));geo.setAttribute('aSeed',new THREE.BufferAttribute(seeds,4));
  const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:kind===2||kind===3?THREE.NormalBlending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},uKind:{value:kind},uAccent:{value:accent.clone()},uProgress:{value:0},uWind:{value:1},uPixel:{value:1},uPointer:{value:pointer}},
    vertexShader:`attribute vec4 aSeed;uniform float uTime,uProgress,uWind,uPixel;uniform int uKind;uniform vec3 uPointer;varying vec4 vSeed;varying float vAlpha;void main(){vSeed=aSeed;vAlpha=1.;vec3 p=position;float t=uTime;float a=aSeed.x*6.28318;
    if(uKind==0){p=vec3((aSeed.x-.5)*13.,aSeed.y*7.-1.,(aSeed.z-.5)*7.);p+=vec3(sin(t*.4+a)*.7*uWind,sin(t*.6+aSeed.z*6.),cos(t*.3+a));vAlpha=.35+.65*pow(.5+.5*sin(t*1.5+a),2.);}
    if(uKind==1||uKind==2){float fall=mod(aSeed.y*10.-t*(.55+aSeed.z*.65),10.);p=vec3((aSeed.x-.5)*13.+sin(t*.5+a)*uWind,fall-2.,(aSeed.z-.5)*8.);}
    if(uKind==3){float age=mod(t+aSeed.w*.5,5.);p=vec3(cos(a)*age*(1.+aSeed.z*2.),-1.+age*(5.+aSeed.y*2.)-age*age*1.5,sin(a)*age*2.);vAlpha=1.-smoothstep(3.2,5.,age);}
    if(uKind==4){vec3 scatter=vec3((aSeed.x-.5)*16.,(aSeed.y-.5)*10.+2.,(aSeed.z-.5)*9.);scatter+=vec3(sin(t+a),cos(t*.7+a),sin(t*.4+a));p=mix(scatter,position,uProgress);vAlpha=.4+.6*uProgress;}
    if(uKind==5){float r=2.35+aSeed.y*.7;float spin=a+t*(.3+aSeed.z*.3)*uWind;p=vec3(cos(spin)*r,2.+sin(spin)*r,(aSeed.z-.5)*.65);vAlpha=.25+.75*aSeed.w;}
    if(uKind==7){float r=1.+aSeed.y*4.;float spin=a+t*.2;p=vec3(cos(spin)*r,1.8+sin(spin*2.+t)*.65+(aSeed.w-.5)*2.,sin(spin)*r*.6);p=mix(p,uPointer,.3+.2*sin(t*.8+a));}
    if(uKind==6)vAlpha=.06+.94*aSeed.w;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;float sz=uKind==2||uKind==3?65.:uKind==4?20.:30.;gl_PointSize=clamp(sz*(.5+aSeed.w)*uPixel/max(1.,-mv.z),1.,32.);}`,
    fragmentShader:`uniform int uKind;uniform float uTime;uniform vec3 uAccent;varying vec4 vSeed;varying float vAlpha;void main(){vec2 uv=gl_PointCoord-.5;float alpha;vec3 col=uAccent;
    if(uKind==2||uKind==3){float a=uTime*(.5+vSeed.z)+vSeed.x*6.28;uv=mat2(cos(a),-sin(a),sin(a),cos(a))*uv;uv.x/=max(.18,abs(sin(a)));if(uKind==2){alpha=1.-smoothstep(.25,.45,length(uv*vec2(1.,.7)));col=mix(uAccent,vec3(1.,.8,.85),vSeed.y);}else{alpha=1.-smoothstep(.2,.25,max(abs(uv.x),abs(uv.y)*1.7));col=mix(.5+.5*cos(vec3(0.,2.,4.)+vSeed.x*6.28),uAccent,.25);}}
    else {float d=length(uv);alpha=pow(max(0.,1.-d*2.),1.6);col=mix(uAccent,vec3(1.),.3);}
    if(alpha<.015)discard;gl_FragColor=vec4(col*(uKind==2||uKind==3?1.:1.7),alpha*vAlpha);}`});
  const m=new THREE.Points(geo,mat);m.frustumCulled=false;root.add(m);particleSets.push({geo,mat,count});return m;
}
function stageBase(){const floor=mesh(new THREE.CylinderGeometry(5,5.15,.12,80),0x10232e);floor.position.y=-1.6;ring(5,-1.52);ring(4.8,-1.52);}
function makeProduct(){
 stageBase();const parts=[];const core=glow(new THREE.CylinderGeometry(.6,.6,2.4,40));core.position.y=.5;
 for(let i=0;i<16;i++){const a=i/16*TAU;const m=mesh(new THREE.BoxGeometry(.32,2.4,.36),0x537783);m.rotation.y=-a;m.position.set(Math.cos(a)*1.15,.5,Math.sin(a)*1.15);parts.push({m,end:m.position.clone(),start:new THREE.Vector3(Math.cos(a)*4,.5+(i%3-1)*1.4,Math.sin(a)*4)});}
 for(let i=0;i<3;i++){const m=mesh(new THREE.CylinderGeometry(1.6,1.6,.18,48),0x2b5362);m.position.y=-.9+i*1.4;parts.push({m,end:m.position.clone(),start:new THREE.Vector3(0,-1+i*3,0)});}
 const bands=[ring(1.75,-.8),ring(1.75,.6),ring(1.75,2)];const flow=points(1500,5);flow.scale.set(.62,.62,.62);flow.rotation.x=Math.PI/2;flow.position.y=.6;
 updateScene=()=>{const p=cyc(t);const assembly=alternate?0:ease(Math.min(p*3.5,(1-p)*5));parts.forEach(({m,end,start},i)=>m.position.lerpVectors(start,end,ease(assembly*1.35-i*.014)));core.material.opacity=.12+assembly*.7;bands.forEach((m,i)=>{m.rotation.z=t*.4*(i%2?1:-1);m.material.opacity=.15+assembly*.6;});flow.visible=assembly>.8;$('#phase').textContent=alternate?'拆解视图 · 拖动观察内部':assembly<.95?'零件对位与组装':'核心启动 · 环形能量运行';};
}
function textTargets(){const c=document.createElement('canvas');c.width=700;c.height=220;const ctx=c.getContext('2d');ctx.font='900 170px Arial';ctx.textAlign='center';ctx.fillStyle='white';ctx.fillText('NOVA',350,165);const px=ctx.getImageData(0,0,700,220).data,result=[];for(let y=20;y<200;y+=3)for(let x=20;x<680;x+=3)if(px[(y*700+x)*4+3]>100)result.push([(x-350)/65,(110-y)/65+2,0]);return result.map((p,i)=>({p,k:seed(i)})).sort((a,b)=>a.k-b.k).map(x=>x.p);}
function makeLogo(){const targets=textTargets();const p=points(targets.length,4,targets);ring(4,-1.45);const halo=glow(new THREE.TorusGeometry(3.7,.018,5,120));halo.position.y=1.8;updateScene=()=>{const x=cyc(t),q=ease(Math.min(x*4,(1-x)*4));p.material.uniforms.uProgress.value=alternate?1-q:q;halo.rotation.z=t*.06;$('#phase').textContent=p.material.uniforms.uProgress.value>.9?'品牌停留 · 可切换聚散':'星尘 ↔ 品牌字样';};}
function makeNetwork(){
 const nodes=[],positions=[[-4,0,0],[-2,1.7,0],[0,0,0],[2,1.7,0],[4,0,0]].map(p=>new THREE.Vector3(...p));const names=selected.id==='education'?['发送端','编码','传输','解码','接收端']:['源点','节点 A','节点 B','节点 C','终点'];
 positions.forEach((p,i)=>{const m=mesh(new THREE.IcosahedronGeometry(.36,1),0x315568);m.position.copy(p);nodes.push(m);const r=ring(.6);r.rotation.x=0;r.position.copy(p);label(names[i],p.clone().add(new THREE.Vector3(0,-.8,0)));});
 const curves=[];for(let i=0;i<4;i++){const mid=positions[i].clone().lerp(positions[i+1],.5).add(new THREE.Vector3(0,1,0));const curve=new THREE.QuadraticBezierCurve3(positions[i],mid,positions[i+1]);curves.push(curve);const tube=glow(new THREE.TubeGeometry(curve,40,.025,5,false));tube.material.opacity=.35;}
 const stream=points(700,6),a=stream.geometry.attributes.position;const v=new THREE.Vector3();
 updateScene=()=>{const progress=alternate?1-cyc(t):cyc(t);for(let i=0;i<700;i++){const u=((progress*4-i*.008)%4+4)%4;curves[Math.floor(u)].getPoint(u%1,v);a.setXYZ(i,v.x,v.y+Math.sin(i)*.035,v.z);}a.needsUpdate=true;nodes.forEach((m,i)=>{const k=Math.abs(progress*4-i)<.45;m.material.emissive.copy(accent).multiplyScalar(k?1.6:.05);m.scale.setScalar(k?1.3:1);});$('#phase').textContent=`${alternate?'反向':'正向'}传递 · ${names[Math.min(4,Math.floor(progress*5))]}`;};
}
function makeScan(){stageBase();const towers=[];for(let x=-2;x<=2;x++)for(let z=-1;z<=1;z++){const h=.7+seed(x*19+z*3)*2.3,m=mesh(new THREE.BoxGeometry(.7,h,.7),0x264659);m.position.set(x*1.25,h/2-1.5,z*1.5);const edge=glow(new THREE.EdgesGeometry(m.geometry));root.remove(edge);const lines=new THREE.LineSegments(edge.geometry,edge.material);lines.position.copy(m.position);root.add(lines);towers.push({m,lines});}
 const plane=glow(new THREE.PlaneGeometry(7,5));plane.material.side=THREE.DoubleSide;plane.material.opacity=.09;plane.rotation.y=Math.PI/2;plane.position.y=.8;const line=glow(new THREE.BoxGeometry(.035,5,5));line.material.wireframe=true;line.position.y=.8;
 updateScene=()=>{const x=-3.5+cyc(t)*7;plane.position.x=x;line.position.x=x;towers.forEach(({m,lines})=>{const d=Math.abs(m.position.x-x);m.material.emissive.copy(accent).multiplyScalar(Math.max(0,1-d)*.65);lines.material.opacity=.08+Math.max(0,1-d)*.8;});$('#phase').textContent=`扫描进度 ${Math.round(cyc(t)*100)}% · 暂停可固定检查位置`;};
}
function hands(time,side){const a=time*(alternate?1.8:1.05)+side*.8;return new THREE.Vector3(side*(1.15+.8*Math.cos(a)),1.6+Math.sin(a)*(alternate?1.35:.8),Math.cos(a*1.4)*.8);}
function makeMotion(){
 stageBase();const joints=Array.from({length:10},()=>mesh(new THREE.SphereGeometry(.11,12,8),0xc5dbe1));const head=mesh(new THREE.SphereGeometry(.28,20,16),0xbfd6df);head.position.set(0,2.55,0);const links=[[0,1],[1,2],[2,3],[0,4],[4,5],[0,6],[6,7],[0,8],[8,9]];const bones=links.map(()=>mesh(new THREE.CylinderGeometry(.06,.06,1,8),0x678795));const trail=points(1400,6),attr=trail.geometry.attributes.position,up=new THREE.Vector3(0,1,0),delta=new THREE.Vector3();
 updateScene=()=>{const poses=[new THREE.Vector3(0,.65,0),new THREE.Vector3(0,2.05,0),new THREE.Vector3(-.8,1.7,0),hands(t,-1),new THREE.Vector3(.8,1.7,0),hands(t,1),new THREE.Vector3(-.45,-.3,0),new THREE.Vector3(-.7,-1.45,.2),new THREE.Vector3(.45,-.3,0),new THREE.Vector3(.7,-1.45,-.2)];joints.forEach((m,i)=>m.position.copy(poses[i]));bones.forEach((m,i)=>{const [a,b]=links[i];delta.subVectors(poses[b],poses[a]);m.position.copy(poses[a]).lerp(poses[b],.5);m.scale.y=delta.length();m.quaternion.setFromUnitVectors(up,delta.normalize());});for(let i=0;i<1400;i++){const side=i%2?1:-1,age=Math.floor(i/2)/700*2.1,p=hands(t-age,side);attr.setXYZ(i,p.x+(seed(i)-.5)*.06,p.y+(seed(i+1)-.5)*.06,p.z);}attr.needsUpdate=true;$('#phase').textContent=alternate?'动作 B · 大幅挥臂':'动作 A · 双手环绕';};
}
function makePortal(interactive=false){
 const p=points(4500,interactive?7:5);const bands=[];for(let i=0;i<4;i++){const r=glow(new THREE.TorusGeometry(2.4+i*.23,.018,5,120));r.position.y=2;bands.push(r);}
 const ticks=new THREE.Group();root.add(ticks);for(let i=0;i<36;i++){const a=i/36*TAU;const m=glow(new THREE.BoxGeometry(.025,i%3===0?.22:.09,.04));root.remove(m);ticks.add(m);m.position.set(Math.cos(a)*3.3,Math.sin(a)*3.3,0);m.rotation.z=a-Math.PI/2;}ticks.position.y=2;
 const wave=ring(.8,0);wave.rotation.x=0;wave.position.y=2;wave.visible=false;
 updateScene=()=>{ticks.rotation.z=t*.15*(alternate?-1:1);bands.forEach((m,i)=>{m.rotation.y=interactive?Math.sin(t*.4+i)*.35:Math.sin(t*.3+i)*.12;m.scale.setScalar(1+Math.sin(t+i)*.02);});const age=t-pulse;wave.visible=age>=0&&age<3;if(wave.visible){wave.scale.setScalar(1+age*4);wave.material.opacity=(1-age/3)*.9;}p.material.uniforms.uWind.value=alternate?-1:1;$('#phase').textContent=interactive?'移动鼠标吸引星群 · 点击产生波纹':'环带与旋涡 · 可切换旋向';};
}
function makeAmbient(){points(4500,selected.mode);if(selected.mode===0){for(let i=0;i<6;i++)ring(.7+i*.5,-1.7).material.opacity=.07;}updateScene=()=>{$('#phase').textContent=selected.mode===3?'循环喷发 · 拖动进度观察抛物线':`${alternate?'反向':'正向'}风场 · 调整密度比较氛围`;};}
function clear(){if(!root)return;const geometries=new Set(),mats=new Set();root.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>mats.add(m));});geometries.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());scene.remove(root);materials=[];particleSets=[];labels=[];$('#labels').replaceChildren();}
function select(id){
 selected=items.find(x=>x.id===id)||items.find(x=>x.id==='product');group=selected.group;t=0;paused=false;alternate=false;pulse=-100;$('#play').textContent='暂停';accent.set(selected.color||'#66e3cf');$('#color').value=selected.color||'#66e3cf';document.documentElement.style.setProperty('--accent',$('#color').value);
 ['title','subtitle','purpose','description','extension','boundary'].forEach(key=>$(key==='subtitle'?'#subtitle':'#'+key).textContent=key==='subtitle'?selected.sub:selected[key]);$('#kind').textContent=group==='scenes'?'APPLICATION SCENARIO':'EFFECT STUDY';$('#special').textContent=selected.action;
 clear();root=new THREE.Group();scene.add(root);const builders={product:makeProduct,logo:makeLogo,network:makeNetwork,scan:makeScan,motion:makeMotion,ambient:makeAmbient,portal:()=>makePortal(false),interactive:()=>makePortal(true)};builders[selected.type]();
 camera.position.set(0,selected.type==='product'||selected.type==='scan'?6:3.8,16);controls.target.set(0,1,0);controls.update();resize();renderCatalog();history.replaceState(null,'','#'+selected.id);updateScene();
}
function renderCatalog(){['effects','scenes'].forEach(g=>$('#'+g+'Tab').classList.toggle('selected',g===group));$('#catalog').innerHTML=items.filter(x=>x.group===group).map((x,i)=>`<button data-id="${x.id}" class="${selected?.id===x.id?'selected':''}" aria-pressed="${selected?.id===x.id}"><em>${String(i+1).padStart(2,'0')}</em><strong>${x.title}</strong><span>${x.sub}</span></button>`).join('');}
function resize(){if(!renderer)return;const r=$('#stage').getBoundingClientRect();renderer.setSize(r.width,r.height,false);composer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.fov=camera.aspect<1?65:48;camera.updateProjectionMatrix();}
function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.05);if(!paused)t+=dt*speed;updateScene();particleSets.forEach(({geo,mat,count})=>{geo.setDrawRange(0,Math.floor(count*density));mat.uniforms.uTime.value=t;mat.uniforms.uWind.value=alternate?-1:1;mat.uniforms.uAccent.value.copy(accent);mat.uniforms.uPixel.value=renderer.getPixelRatio();});materials.forEach(m=>m.color.copy(accent));controls.update();for(const {el,position} of labels){const p=position.clone().project(camera);el.style.left=(p.x*.5+.5)*100+'%';el.style.top=(-p.y*.5+.5)*100+'%';el.hidden=p.z>1;}$('#progress').value=cyc(t)*100;$('#progressValue').textContent=Math.round(cyc(t)*100)+'%';$('#renderState').textContent=paused?'已暂停 · 参数仍可调整':'实时渲染 · '+(group==='scenes'?'场景演示':'特效素材');composer.render();}
function boot(){
 renderer=new THREE.WebGLRenderer({canvas:$('#viewport'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;scene=new THREE.Scene();scene.background=new THREE.Color('#080f19');scene.fog=new THREE.FogExp2('#080f19',.026);camera=new THREE.PerspectiveCamera(48,1,.1,100);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=7;controls.maxDistance=35;scene.add(new THREE.HemisphereLight(0xccefff,0x132331,2.4));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(3,7,5);scene.add(key);const rim=new THREE.DirectionalLight(0x4598ff,2);rim.position.set(-5,3,-3);scene.add(rim);
 composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(800,600),.65,.45,.8));composer.addPass(new OutputPass());new ResizeObserver(resize).observe($('#stage'));
 $('#catalog').onclick=e=>{const b=e.target.closest('[data-id]');if(b)select(b.dataset.id);};$('#effectsTab').onclick=()=>select('fireflies');$('#scenesTab').onclick=()=>select('product');$('#play').onclick=()=>{paused=!paused;$('#play').textContent=paused?'继续':'暂停';};$('#reset').onclick=()=>{t=0;pulse=-100;};$('#speed').oninput=e=>{speed=Number(e.target.value);$('#speedValue').textContent=speed.toFixed(1)+'×';};$('#density').oninput=e=>{density=Number(e.target.value);$('#densityValue').textContent=Math.round(density*100)+'%';};$('#color').oninput=e=>{accent.set(e.target.value);document.documentElement.style.setProperty('--accent',e.target.value);};$('#progress').oninput=e=>{t=Math.min(Number(e.target.value)/100*duration,duration-0.000001);paused=true;$('#play').textContent='继续';};$('#special').onclick=()=>{if(selected.type==='interactive'){pulse=t;}else if(selected.type==='scan'||selected.mode===3){t=0;paused=false;$('#play').textContent='暂停';}else alternate=!alternate;};
 const ray=new THREE.Raycaster(),plane=new THREE.Plane(new THREE.Vector3(0,0,1),0),ndc=new THREE.Vector2();renderer.domElement.addEventListener('pointermove',e=>{const r=renderer.domElement.getBoundingClientRect();ndc.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(ndc,camera);ray.ray.intersectPlane(plane,pointer);});let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(selected.type==='interactive'&&down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<6)pulse=t;down=null;});
 select(location.hash.slice(1)||'product');frame();
}
try{boot();}catch(error){console.error(error);$('#error').hidden=false;$('#error').textContent='三维场景启动失败：'+error.message+'。请使用支持 WebGL 的浏览器。';$('#renderState').textContent='加载失败';}
